module.exports = {
    HTTP_UNATHORIZED: 401,
    MAX_CHARS_LOG_PER_STRING: 256,
    HEADER_CORRELATION_ID: "x-correlation-id",
    SENSITIVE_KEYS: ['password', 'token', 'accesstoken', 'refreshtoken', 'authorization', 'purchasetoken', 'offertoken', 'verificationcode', 'fcmtoken'],
    MASK_SENSITIVE_KEYS: '**********',
    ALPHABET_NUMBERS: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",
    PASSWORD_PATTERN: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$",
    BASIC_PLAN_LIKES_PER_DAY: "BASIC_PLAN_LIKES_PER_DAY",
    ERROR_GENERIC_RESPONSE: "ERROR_GENERIC_RESPONSE",
    ERROR_UNAUTHORIZED: "ERROR_UNAUTHORIZED",
    ERROR_BAD_REQUEST_RESPONSE: "ERROR_BAD_REQUEST_RESPONSE",
    ERROR_GENERIC_LOGGING_RESPONSE: "ERROR_GENERIC_LOGGING_RESPONSE",
    SUCCESS_REGISTER_WALLET: "SUCCESS_REGISTER_WALLET",
    SUCCESS_VERIFY_CODE_USER: "SUCCESS_VERIFY_CODE_USER",
    JPEG_EXTENSION: "jpeg",
    PNG_EXTENSION: "png",
    WEBP_EXTENSION: "webp",
    LANGUAGE_ES: "es",
    LANGUAGE_EN: "en",
    REDIS_TRUE: "1",
    STATUS_ACTIVE: "A",
    STATUS_INACTIVE: "I",
    STATUS_DESC_ACTIVE: "active",
    STATUS_DESC_INACTIVE: "inactive",
    STATUS_DESC_DELETING: "deleting",
    REDIS_FALSE: "0",
    WS_EVENT_OPEN_CHAT: "openChat",
    WS_EVENT_MESSAGE_READ: "messageRead",
    WS_EVENT_SEND_MESSAGE: "sendMessage",
    WS_EVENT_UPDATE_MESSAGE: "updateMessage",
    WS_EVENT_NEW_MESSAGE: "newMessage",
    WS_EVENT_NEW_UPDATE_MESSAGE: "newUpdateMessage",
    WS_EVENT_NEW_LIKE: "newLike",
    WS_EVENT_NEW_MATCH: "newMatch",
    UNKNOWN_NOTIFICATION_TYPE: "Unknown notification type",
    DEFAULT_SORTING_BY_NAME: { "language.0.name": 1 },
};
